"""criar tabela historicos

Revision ID: b47e8b82b091
Revises: ec4cf7af8209
Create Date: 2026-07-18 08:26:12.210140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47e8b82b091'
down_revision = 'ec4cf7af8209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_atendimento', sa.Date(), nullable=False),
    sa.Column('tipo_atendimento', sa.String(length=100), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tratamento', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=True),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['veterinario_id'], ['veterinarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historicos')
    # ### end Alembic commands ###
