"""cria tabela horarios_veterinarios

Revision ID: 24aa2240351a
Revises: bae665e37889
Create Date: 2026-07-27 19:38:30.552627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24aa2240351a'
down_revision = 'bae665e37889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios_veterinarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('inicio_almoco', sa.Time(), nullable=True),
    sa.Column('fim_almoco', sa.Time(), nullable=True),
    sa.Column('intervalo_minutos', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['veterinario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    

    # ### end Alembic commands ###


def downgrade():
   
    op.drop_table('horarios_veterinarios')
    # ### end Alembic commands ###
