"""remove armazenamento binario de arquivos

Revision ID: 4aeb816217c7
Revises: 97e689906dfb
Create Date: 2026-08-18 20:06:08.208277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4aeb816217c7'
down_revision = '97e689906dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_column('dados')
        batch_op.drop_column('miniatura')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('miniatura', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dados', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
