"""adiciona dados profissionais aos usuarios

Revision ID: 6c9fe05d9632
Revises: 90db25fb74cc
Create Date: 2026-07-24 21:41:09.425742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9fe05d9632'
down_revision = '90db25fb74cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crmv', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('especialidade', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_crmv'), ['crmv'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_crmv'))
        batch_op.drop_column('especialidade')
        batch_op.drop_column('crmv')

    # ### end Alembic commands ###
