"""adiciona metadados de processamento de imagens

Revision ID: 7fd06330a8e3
Revises: ec4213a65c6c
Create Date: 2026-07-21 18:04:13.623075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fd06330a8e3'
down_revision = 'ec4213a65c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualidade', sa.SmallInteger(), nullable=False))
        batch_op.add_column(sa.Column('modelo_compactacao', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('versao_processador', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('orientacao_corrigida', sa.Boolean(), nullable=False))

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('atualizado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.alter_column('atualizado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_column('orientacao_corrigida')
        batch_op.drop_column('versao_processador')
        batch_op.drop_column('modelo_compactacao')
        batch_op.drop_column('qualidade')

    # ### end Alembic commands ###
