"""cria tabela exames

Revision ID: 90db25fb74cc
Revises: 04aea8325a8a
Create Date: 2026-07-22 19:08:07.396193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90db25fb74cc'
down_revision = '04aea8325a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historico_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_exame', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['historico_id'], ['historicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exames')
    # ### end Alembic commands ###
