"""permite arquivos armazenados fora do banco

Revision ID: 97e689906dfb
Revises: da2896d4a96f
Create Date: 2026-08-18 19:23:58.037016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97e689906dfb'
down_revision = 'da2896d4a96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.alter_column('dados',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.alter_column('dados',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
