"""adiciona vinculacao oauth aos usuarios

Revision ID: bfeadff8d4b1
Revises: 4aeb816217c7
Create Date: 2026-08-24 17:41:20.461612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfeadff8d4b1'
down_revision = '4aeb816217c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('provedor', sa.String(length=20), nullable=False),
    sa.Column('provedor_usuario_id', sa.String(length=255), nullable=False),
    sa.Column('email_provedor', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provedor', 'provedor_usuario_id', name='uq_conta_oauth_provedor_usuario')
    )
    with op.batch_alter_table('contas_oauth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contas_oauth_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas_oauth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_oauth_usuario_id'))

    op.drop_table('contas_oauth')
    # ### end Alembic commands ###
