"""adiciona estrutura de arquivos e fotos

Revision ID: ec4213a65c6c
Revises: 7e04c160d860
Create Date: 2026-07-21 17:38:37.392400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec4213a65c6c'
down_revision = '7e04c160d860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('extensao', sa.String(length=20), nullable=False),
    sa.Column('dados', sa.LargeBinary(), nullable=False),
    sa.Column('miniatura', sa.LargeBinary(), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('tamanho_miniatura_bytes', sa.Integer(), nullable=True),
    sa.Column('largura', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('largura_miniatura', sa.Integer(), nullable=True),
    sa.Column('altura_miniatura', sa.Integer(), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arquivos_hash_sha256'), ['hash_sha256'], unique=False)

    op.create_table('fotos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotos_usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotos_usuarios_arquivo_id'), ['arquivo_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fotos_usuarios_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('fotos_pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.SmallInteger(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('posicao >= 1 AND posicao <= 3', name='ck_foto_pet_posicao_entre_1_e_3'),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id', 'posicao', name='uq_foto_pet_pet_posicao')
    )
    with op.batch_alter_table('fotos_pets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotos_pets_arquivo_id'), ['arquivo_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fotos_pets_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index('uq_foto_pet_principal_por_pet', ['pet_id'], unique=True, postgresql_where=sa.text('principal = true'))

    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('fotos_pets', schema=None) as batch_op:
        batch_op.drop_index('uq_foto_pet_principal_por_pet', postgresql_where=sa.text('principal = true'))
        batch_op.drop_index(batch_op.f('ix_fotos_pets_pet_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_pets_arquivo_id'))

    op.drop_table('fotos_pets')
    with op.batch_alter_table('fotos_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotos_usuarios_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_usuarios_arquivo_id'))

    op.drop_table('fotos_usuarios')
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arquivos_hash_sha256'))

    op.drop_table('arquivos')
    # ### end Alembic commands ###
