"""adicionar veterinario ao agendamento

Revision ID: ec4cf7af8209
Revises: 08c70d4b7677
Create Date: 2026-07-17 20:01:10.265849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4cf7af8209'
down_revision = '08c70d4b7677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('veterinario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'veterinarios', ['veterinario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('veterinario_id')

    # ### end Alembic commands ###
